"""Persistence operations for digests and their selected articles."""

from dataclasses import replace
from datetime import datetime
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain import Digest, DigestItem, DigestStatus, ErrorCode, NewsItemStatus
from app.infrastructure.db.models import DigestItemModel, DigestModel, NewsItemModel
from app.texts.db import (
    DIGEST_CANDIDATES_REQUIRED,
    DIGEST_GENERATED_REQUIRED,
    DIGEST_NEWS_MISSING,
    DIGEST_NOT_FOUND,
)


class DigestRepository:
    """Persist digest aggregates through a caller-owned session."""

    def __init__(self, session: AsyncSession) -> None:
        """Bind repository operations to one session."""
        self._session = session

    async def create_generated(self, digest: Digest) -> Digest:
        """Create a digest and consume its candidates as one atomic operation.

        Selected articles are locked in ID order to avoid inconsistent
        lock ordering across concurrent creations. A failed operation rolls
        back its savepoint without committing the surrounding transaction.
        """
        validated = replace(
            digest,
            items=tuple(
                sorted(
                    (replace(item) for item in digest.items),
                    key=lambda item: item.position,
                )
            ),
        )

        if validated.status is not DigestStatus.GENERATED:
            raise ValueError(DIGEST_GENERATED_REQUIRED)

        selected_ids = [item.news_item_id for item in validated.items]

        async with self._session.begin_nested():
            statement = (
                select(NewsItemModel)
                .where(NewsItemModel.id.in_(selected_ids))
                .order_by(NewsItemModel.id.asc())
                .with_for_update()
                .execution_options(populate_existing=True)
            )
            news_models = list(await self._session.scalars(statement))

            if len(news_models) != len(selected_ids):
                raise LookupError(DIGEST_NEWS_MISSING)

            if any(model.status is not NewsItemStatus.CANDIDATE for model in news_models):
                raise ValueError(DIGEST_CANDIDATES_REQUIRED)

            model = DigestModel(
                id=validated.id,
                run_id=validated.run_id,
                digest_date=validated.digest_date,
                title=validated.title,
                status=validated.status,
                rendered_text=validated.rendered_text,
                model=validated.model,
                prompt_version=validated.prompt_version,
                provider_response_id=validated.provider_response_id,
                input_tokens=validated.input_tokens,
                output_tokens=validated.output_tokens,
                created_at=validated.created_at,
                sent_at=validated.sent_at,
                error_code=validated.error_code,
                error_summary=validated.error_summary,
            )
            self._session.add(model)
            await self._session.flush()

            self._session.add_all(
                [
                    DigestItemModel(
                        digest_id=validated.id,
                        news_item_id=item.news_item_id,
                        position=item.position,
                        summary=item.summary,
                        tag=item.tag,
                        relevance_score=item.relevance_score,
                        selection_reason=item.selection_reason,
                    )
                    for item in validated.items
                ]
            )
            await self._session.flush()

            for news_model in news_models:
                news_model.status = NewsItemStatus.USED
                news_model.ignore_reason = None

            await self._session.flush()

        return validated

    async def get(self, digest_id: UUID) -> Digest | None:
        """Return a digest with articles ordered by their positions."""
        model = await self._session.get(DigestModel, digest_id)
        return await self._restore(model) if model is not None else None

    async def get_by_run(self, run_id: UUID) -> Digest | None:
        """Return the digest generated by a run, or None."""
        statement = select(DigestModel).where(DigestModel.run_id == run_id)
        model = await self._session.scalar(statement)
        return await self._restore(model) if model is not None else None

    async def get_latest(self) -> Digest | None:
        """Return the latest digest by date, creation time, and ID."""
        statement = (
            select(DigestModel)
            .order_by(
                DigestModel.digest_date.desc(),
                DigestModel.created_at.desc(),
                DigestModel.id.desc(),
            )
            .limit(1)
        )
        model = await self._session.scalar(statement)
        return await self._restore(model) if model is not None else None

    async def get_latest_sent(self) -> Digest | None:
        """Return the latest successfully sent digest."""
        statement = (
            select(DigestModel)
            .where(DigestModel.status == DigestStatus.SENT)
            .order_by(
                DigestModel.sent_at.desc().nullslast(),
                DigestModel.digest_date.desc(),
                DigestModel.id.desc(),
            )
            .limit(1)
        )
        model = await self._session.scalar(statement)
        return await self._restore(model) if model is not None else None

    async def transition_to(
        self,
        digest_id: UUID,
        target_status: DigestStatus,
        *,
        occurred_at: datetime | None = None,
        error_code: ErrorCode | None = None,
        error_summary: str | None = None,
    ) -> Digest:
        """Apply a domain-approved delivery transition under the digest lock.

        External delivery calls must occur outside this transaction.
        Error summaries must be sanitized before being supplied.
        """
        statement = (
            select(DigestModel)
            .where(DigestModel.id == digest_id)
            .with_for_update()
            .execution_options(populate_existing=True)
        )
        model = await self._session.scalar(statement)

        if model is None:
            raise LookupError(DIGEST_NOT_FOUND)

        digest = await self._restore(model)
        digest.transition_to(
            target_status,
            occurred_at=occurred_at,
            error_code=error_code,
            error_summary=error_summary,
        )

        model.status = digest.status
        model.sent_at = digest.sent_at
        model.error_code = digest.error_code
        model.error_summary = digest.error_summary

        await self._session.flush()
        return digest

    async def _restore(self, model: DigestModel) -> Digest:
        """Restore a validated digest aggregate without lazy relationship loading."""
        statement = (
            select(DigestItemModel)
            .where(DigestItemModel.digest_id == model.id)
            .order_by(DigestItemModel.position.asc())
        )
        item_models = await self._session.scalars(statement)
        items = tuple(
            DigestItem(
                news_item_id=item.news_item_id,
                position=item.position,
                summary=item.summary,
                tag=item.tag,
                relevance_score=item.relevance_score,
                selection_reason=item.selection_reason,
            )
            for item in item_models
        )

        return Digest(
            id=model.id,
            run_id=model.run_id,
            digest_date=model.digest_date,
            title=model.title,
            status=model.status,
            rendered_text=model.rendered_text,
            model=model.model,
            prompt_version=model.prompt_version,
            items=items,
            provider_response_id=model.provider_response_id,
            input_tokens=model.input_tokens,
            output_tokens=model.output_tokens,
            created_at=model.created_at,
            sent_at=model.sent_at,
            error_code=model.error_code,
            error_summary=model.error_summary,
        )
